#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm

sudo apt-get update
sudo apt-get upgrade -y

sudo apt-get install -y haproxy

sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup


sudo tee /etc/haproxy/haproxy.cfg >/dev/null <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    maxconn 4096
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend estherchikombe.tech
    bind *:8080
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 403773-web-01 54.172.58.162:80 check
    server 403773-web-02 54.209.223.92:80 check
EOF

# Update hostnames for web servers
sudo hostnamectl set-hostname 403773-lb-01


sudo systemctl enable haproxy

sudo systemctl restart haproxy
