#!/usr/bin/env bash
#Displays the PID, along with the process name, that contains the word bash.
#There is a "sleep 2" in between each iteration

while true
do
 echo "To infinity and beyond"
 sleep 2
done
