#!/usr/bin/env bash
#A Bash script that displays Best School 10 times, but for the 9th iteration,
#displays Best School and then Hi on a new line.
#Use the while loop
#Use the if statement

count=0
while [ $count -lt 11 ]
do
	if [ $count = 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	((count+=1))
done
